name: GKE Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_key: ${{ secrets.c9ce64c827237d5900e66e729ccb0692f058a07d}}
        project_id: ${{ secrets.formal-scout-426509-s4 }}

    - name: Authenticate Docker to Google Container Registry
      run: gcloud auth configure-docker

    - name: Build Docker image
      run: docker build -t gcr.io/${{ secrets.formal-scout-426509-s4 }}/simple-api .

    - name: Push Docker image to GCR
      run: docker push gcr.io/${{ secrets.formal-scout-426509-s4}}/simple-api

    - name: Run Terraform
      run: terraform init && terraform apply -auto-approve
